# --- Grafana ConfigMap for Prometheus Datasource ---
# This ConfigMap will be used to automatically configure Grafana
# to connect to a Prometheus service once you deploy it.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service:9090
      access: proxy
      isDefault: true
---
# --- Grafana Deployment ---
# This deploys the Grafana application itself.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources-volume
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-datasources-volume
        configMap:
          name: grafana-datasources
---
# --- Grafana Service ---
# This exposes the Grafana UI so you can access it from your browser.
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    # You can access Grafana on this port from outside the cluster
    nodePort: 32000
